# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:00


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
